#!/bin/sh

# cleanup
rm -rf obj_dir
rm -f lights.vcd

# run Verilator to translate Verilog into C++, including c++ testbench
verilator -Wall --cc --trace lights.sv f1_fsm.sv clktick.sv --exe lights_tb.cpp

# build a c++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f Vlights.mk Vlights

# run executable simulation file 
obj_dir/Vlights